# Generated by Django 3.2.5 on 2021-09-23 19:48

from django.db import migrations
from django.contrib.auth.models import Group

def create_auth_groups(apps, schema_editor):
    customers = Group(name='Customers')
    employees = Group(name='Employees')
    customers.save()
    employees.save()



class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_auth_groups)
    ]
